# Generated by Django 2.0.1 on 2018-08-14 14:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180814_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date(2018, 8, 14), verbose_name='日付'),
        ),
        migrations.AddField(
            model_name='book',
            name='read_flg',
            field=models.IntegerField(default=0, verbose_name='既読フラグ'),
        ),
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
