# Generated by Django 2.0.1 on 2018-08-14 15:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180814_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date(2018, 8, 15), verbose_name='日付'),
        ),
    ]
