# Generated by Django 2.0.1 on 2018-08-14 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20180815_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_flg',
            field=models.IntegerField(choices=[(0, '未読'), (1, '既読')], default=0, verbose_name='既読フラグ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='スコア'),
        ),
    ]
